Fix compatiblity with Python 3.11+
AttributeError: module 'inspect' has no attribute 'getargspec'


See from https://docs.python.org/3.11/whatsnew/3.11.html#removed

Removed from the inspect module:

> the getargspec function, deprecated since Python 3.0; use inspect.signature() or inspect.getfullargspec() instead.

Downstream bug report: https://bugzilla.redhat.com/show_bug.cgi?id=2095027